//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Advanced Params.
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bad Lat/Lng.
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Basic Tuning.
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot graph this field.
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cant detect your Board version. Please check your cabling.
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Checking .
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Check port settings or Port in use?.
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Command failed to execute
        ///.
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Communication Error - no connection.
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONNECT.
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connect Failed.
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connecting Mavlink.
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description: .
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detected a.
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detecting Board Version.
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DISCONNECT.
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Downloaded from internet.
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Downloading from Internet.
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue?.
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Epprom format changed ({0) vs {1}).
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error closing log files.
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error communicating with the autopilot.
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error Connecting
        ///.
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This feature is not enabled in your firmware..
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error loading firmware file.
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error receiving log list.
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error: no responce from MAV.
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are not connected..
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error receiving list
        ///.
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error: command rejected by MAV.
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error renaming file.
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error setting parameter .
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set {0} Failed.
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extended Tuning.
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to create log - wont log this session.
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed download.
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed read HEX.
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to read firmware.hex :.
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed upload.
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flight Modes.
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full Parameter List.
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full Parameter Tree.
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GeoFence.
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting .
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting FW List.
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting FW Version.
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting Params.
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting Params....
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting updated parameters.
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Got param .
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Alt.
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid BaudRate.
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Board Type.
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Field.
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid FileName.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid number entered
        ///.
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Pan Range.
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid PortName.
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Tilt Range.
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Update Rate.
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Link Stats.
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please click ok and move the autopilot around all axises in a circular motion.
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mavlink Connecting....
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are missing data points. do you want to run the calibration anyway?.
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Firmware.
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New firmware available
        ///.
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No FMT message for .
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Only 1 Heatbeat Received.
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting.
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please connect first.
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please connect and backup your config in the configuration tab..
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please load a valid file.
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select a cell first.
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///Please upgrade.
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sucessfully programmed.
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Raw Param Warning.
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings.
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading Hex.
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading Hex File.
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Received List.
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a run anyway.
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select a comport.
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show me again?.
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard Params.
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your model is still moving are you sure you want to disconnect?.
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timeout waiting for autoscan/no mavlink device connected.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trying to connect.
        ///Timeout in {0}.
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Units: {0}{1}.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Found
        ///
        ///Do you wish to update now? [link;.
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload Complete.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uploading {0} bytes to Board:.
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload succeeded, but verify failed: exp {0} got {1} at .
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify Complete.
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify Firmware.
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter.
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration..
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log..
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning rally points are located greater than RALLY_LIMIT_KM.
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        ///.
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
    }
}
