//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMap.NET.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMap.NET.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AMap.
        /// </summary>
        internal static string AMap {
            get {
                return ResourceManager.GetString("AMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AMapSatellite.
        /// </summary>
        internal static string AMapSatellite {
            get {
                return ResourceManager.GetString("AMapSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BingHybridMap.
        /// </summary>
        internal static string BingHybridMap {
            get {
                return ResourceManager.GetString("BingHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BingMap.
        /// </summary>
        internal static string BingMap {
            get {
                return ResourceManager.GetString("BingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BingSatelliteMap.
        /// </summary>
        internal static string BingSatelliteMap {
            get {
                return ResourceManager.GetString("BingSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleChinaHybridMap.
        /// </summary>
        internal static string GoogleChinaHybridMap {
            get {
                return ResourceManager.GetString("GoogleChinaHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleChinaMap.
        /// </summary>
        internal static string GoogleChinaMap {
            get {
                return ResourceManager.GetString("GoogleChinaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleChinaSatelliteMap.
        /// </summary>
        internal static string GoogleChinaSatelliteMap {
            get {
                return ResourceManager.GetString("GoogleChinaSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleChinaTerrainMap.
        /// </summary>
        internal static string GoogleChinaTerrainMap {
            get {
                return ResourceManager.GetString("GoogleChinaTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleHybridMap.
        /// </summary>
        internal static string GoogleHybridMap {
            get {
                return ResourceManager.GetString("GoogleHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleMap.
        /// </summary>
        internal static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleSatelliteMap.
        /// </summary>
        internal static string GoogleSatelliteMap {
            get {
                return ResourceManager.GetString("GoogleSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoogleTerrainMap.
        /// </summary>
        internal static string GoogleTerrainMap {
            get {
                return ResourceManager.GetString("GoogleTerrainMap", resourceCulture);
            }
        }
    }
}
